_target_: src.models.comp_module.CompLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: ${model.hparams.lr}
  weight_decay: 1e-8
  amsgrad: false

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.8
  min_lr: 1.0e-07
  patience: 3

net:
  _target_: src.models.components.molcomp.model.MolWrapper
  input_node_dim: 8 
  input_edge_dim: 6 
  pos_noise_std: 0.05
  node_dim: 128
  edge_dim: 32
  time_dim: 10
  poc_dim: 10
  bond_len_loss: False
  loss_filename: ./losses.txt 
  denoiser:
    backbone: NodeEdgeNet
    num_blocks: 3
    cutoff: 15
    use_gate: True
  diff:
    num_timesteps: 1000
    time_dim: 10
    diff_pos:
      beta_schedule: advance
      scale_start: 0.9999
      scale_end: 0.0001
      width: 3
    diff_atom: 
      init_prob: tomask
      beta_schedule: advance
      scale_start: 0.9999
      scale_end: 0.0001
      width: 3
    diff_bond:
      init_prob: absorb
      beta_schedule: advance
      scale_start: 0.9999
      scale_end: 0.0001
      width: 3
  sample:
    num_mols: 100
    guidance: null


compile: false

hparams:
  lr_warmup_steps: 30000
  lr: 1.e-4
